[package]
name = "watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
daemonize = "0.5.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "1.44.2", features = ["full"] }
